version: "2.1"

volumes:
  databasevol:

services:
  shareapp:
    build: ./Abschlussprojekt
    ports: 
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: sharepw
      MYSQL_DATABASE: sharingdatabase
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=example"]
      interval: 10s
      timeout: 5s
      retries: 5

  propay:
    image: propra/propay
    ports:
      - "8888:8888"
    # Optional